fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: ruff
        name: ruff
        stages: [commit]
        language: system
        entry: poetry run ruff --fix --show-fixes
        types: [python]
